config/routes.rb
Rails.application.routes.draw do
  resources :equipments
  resources :dealers
  resources :items
  resources :services
  resources :billings
  resources :maintenances
  # devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'home/index'
  root 'home#index'
  get 'acknowledgement', to: 'maintenances#acknowledgement'
  get 'followup', to: 'maintenances#followup'
  get 'survey', to: 'home#survey'
  get 'service', to: 'home#service', as: 'all_service'
  get 'search', to: 'equipments#search'
  get 'download_pdf', to: "home#download_pdf"
  get 'about', to: "home#about"
  get 'staff', to: "home#staff"
  get 'summary', to: "home#summary"
  get 'dashboard', to: "home#dashboard"
  put 'maintenance_cancel_request/:id', to: "maintenances#cancel_request", as: 'maintenance_cancel_request'
  get 'cancel_request_received/:id', to: 'maintenances#cancel_request_received', as: 'cancel_request_received'
  get 'equipments/:id/archive/', to: "equipments#archive", as: 'archive_equipment'
  get 'equipments/:id/unarchive/', to: "equipments#unarchive", as: 'unarchive_equipment'
  get 'sign_up_confirmation', to: 'home#sign_up_confirmation', as: 'sign_up_confirmation'
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    belongs_to :user
    has_many :maintenances

    enum additional_info: [:user_manual, :technical_manual, :inspection_certificate, :calibration_certificate, :installed_and_commissioned]
    enum status:  { working: 0, repairable: 1, abandoned: 2}

    paginates_per 50

end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]
  before_action :set_search

  def set_search
    @q = Equipment.ransack(params[:q]) 
    @search_equipments = @q.result(distinct: true).where(archived: false).page(params[:page])
    @search_archived_equipments = @q.result(distinct: true).where(archived: true).page(params[:page])
  end 

  # GET /equipments
  # GET /equipments.json
  def index
    @equipments = Equipment.all
  end

  # GET /equipments/1
  # GET /equipments/1.json
  def show
  end

  # GET /equipments/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipments/1/edit
  def edit
  end

  # POST /equipments
  # POST /equipments.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipments/1
  # PATCH/PUT /equipments/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        # format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.html { render :index }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipments/1
  # DELETE /equipments/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipments_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def archive
    @equipment = Equipment.find_by_id(params[:id])
    @equipment.update(archived: true)
    redirect_to :equipments
  end

  def unarchive
    @equipment = Equipment.find_by_id(params[:id])
    @equipment.update(archived: false)
    redirect_to :equipments
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:user_id, :name, :name_of_model, :model_number, :serial_number, :inventory_number, :acquired_year, :location, :manufacturer, :country_of_origin, :warranty_period, :additional_info, :other_info, :dealer_id, :internal_number, :remark, :price, :description, :quantity, :where_purchased, :department_id, :status, :archived)
    end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipments/_form.html.erb
<%= form_with(model: equipment, local: true) do |form| %>

  <% if equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% equipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :user_id, value: current_user.id, style: 'display:none' %>

  <div class="field">
    <%= form.label :name , class: 'label' %>
    <%= form.text_field :name , class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :department_id, class: 'label' %>
    <%= form.collection_select :department_id, Department.all, :id, :name, include_blank: true %>
  </div>
  
  <div class="field">
    <%= form.label 'Model name', class: 'label' %>
    <%= form.text_field :name_of_model , class: 'input', value: '' %>
  </div>

  <div class="field">
    <%= form.label :model_number , class: 'label' %>
    <%= form.text_field :model_number , class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :serial_number , class: 'label' %>
    <%= form.text_field :serial_number , class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :inventory_number , class: 'label' %>
    <%= form.text_field :inventory_number , class: 'input', placeholder: 'JKU/'%>
  </div>

  <div class="field">
    <%= form.label 'Year acquired', class: 'label' %>
    <%= form.select :acquired_year , 1981 .. Date.today.year ,include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :location , class: 'label' %>
    <%= form.text_field :location , class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :manufacturer , class: 'label' %>
    <%= form.text_field :manufacturer , class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :country_of_origin , class: 'label' %>
    <%= form.country_select :country_of_origin , class: 'input', include_blank: true  %>
  </div>

  <div class="field">
    <%= form.label :warranty_period , class: 'label' %>
    <%= form.text_field :warranty_period , class: 'input' %>
  </div>

  <div class="field">
  <%= form.label 'additional information' , class: 'label' %>
    <% Equipment.additional_infos.each do |key, val| %>
      <%= form.check_box :additional_infos, {:multiple => true}, val, class: 'input' %>
      <%= form.label key , class: 'checkbox' %>
    <% end %>  
  </div>

  <div class="field">
    <%= form.label 'other_information' , class: 'label' %>
    <%= form.text_field :other_info, class: 'input' %>
  </div>


  <div class="actions">
    <%= form.submit 'submit' , class: 'button is-success' %>
  </div>
<% end %>

app/views/equipments/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form', equipment: @equipment %>

app/views/equipments/index.html.erb
<%= search_form_for @q do |f| %>
<div class="field is-horizontal">
  <nav class="panel">
    <div class="panel-block">

      <div class="field-label">
        <%= f.label :name_cont, "Name", class: 'label' %> 
      </div>
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.search_field :name_cont, placeholder: 'Enter name...' , class: 'input name-input' %>
          </p>
        </div>
      </div>

      <div class="field-label" style="margin-left: 20px;">
        <%= f.label :name_of_model_cont, "Model" , class: 'label' %> 
      </div>
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.search_field :name_of_model_cont, placeholder: 'Enter model name...' , class: 'input model-name-input' %>
          </p>
        </div>
      </div>

      <div class="field-label" style="margin-left: 20px;">
        <%= f.label :department_id_eq , "Department" , class: 'label' %> 
      </div>
      <div class="field-body">
        <div class="field">
          <p class="control is-expanded">
            <%= f.select :department_id_eq, Department.all.pluck(:name).zip(Department.all.pluck(:id)), {include_blank: true}, { class: 'department-select'} %>
          </p>
        </div>
      </div>

    </div>

    <div class="panel-block">
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.submit ("Search") , class: 'button is-primary'%>
          <button class="button clear-button">
            Clear
          </button>
        </div>
      </div>
    </div>
  </div>

  </nav>
</div>
<% end %>

<div class="tabs is-boxed">
  <ul>
    <li class="unarchived-equipments is-active">
      <a>
        <span>Equipments</span>
      </a>
    </li>
    <li class="archived-equipments">
      <a>
        <span>Archived equipments</span>
      </a>
    </li>
  </ul>
</div>


<div class="table-wrapper-scroll-y my-custom-scrollbar" style="margin-top:20px; margin-bottom:20px;">

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Department</th>
        <th>Serial number</th>
        <th>inventory number</th>
        <th>Model number</th>
        <th>Manufacturer</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody> 

      <% @search_equipments.each do |equipment| %>
      <tr class="search-equipments-table">
        <td><%= link_to equipment.name , equipment %></td>
        <td><%= Department.find_by_id(equipment.department_id).name %></td>
        <td><%= equipment.serial_number %></td>
        <td><%= equipment.inventory_number %></td>
        <td><%= equipment.model_number %></td>
        <td><%= equipment.manufacturer %></td>
        <%= form_with(model: equipment, remote: true) do |form| %>
        <td><%= form.select :status, Equipment.statuses.keys, {}, {class: 'equipment_status'} %>
          <%= form.submit 'update' , class: 'button is-small update-button' %></td>
          <% end %>
          <% if current_user.role=="admin" %>
          <td><%= link_to 'Edit', edit_equipment_path(equipment), class: 'button is-small is-success' %></td>
          <td><%= link_to 'Archive', archive_equipment_path(equipment),  class: 'button is-danger is-small' %></td>
          <% else %>
          <td><%= link_to 'Request maintenance', new_maintenance_path(:equipment_id => equipment.id), class: 'button is-success' %></td>
          <% end %>
        </tr>
      <% end %>

      <% @search_archived_equipments.each do |_equipment| %>
      <tr class="search-archived-equipments-table">
        <td><%= link_to _equipment.name , _equipment %></td>
        <td><%= Department.find_by_id(_equipment.department_id).name %></td>
        <td><%= _equipment.acquired_year %></td>
        <td><%= _equipment.model_number %></td>
        <td><%= _equipment.location %></td>
        <td><%= _equipment.manufacturer %></td>
        <%= form_with(model: _equipment, remote: true) do |form| %>
        <td><%= form.select :status, Equipment.statuses.keys, {}, {class: 'equipment_status'} %>
          <%= form.submit 'update' , class: 'button is-small update-button' %></td>
          <% end %>
          <% if current_user.role=="admin" %>
          <td><%= link_to 'Edit', edit_equipment_path(_equipment), class: 'button is-small is-success' %></td>
          <td><%= link_to 'Unarchive', unarchive_equipment_path(_equipment),  class: 'button is-info is-small' %></td>
          <% else %>
          <td><%= link_to 'Request maintenance', new_maintenance_path(:equipment_id => _equipment.id), class: 'button is-success' %></td>
          <% end %>
       </tr>
       <% end %>

      </tbody>

    </table>
  </div>

  <%= paginate @search_equipments  %>

app/views/equipments/new.html.erb
<h1 class="is-size-4" style="margin:40px 0;">New Equipment Details (enter all fields)</h1>

<%= render 'form', equipment: @equipment %>

app/views/equipments/search.html.erb
<%= render 'search_form' %>

<div class="table-wrapper-scroll-y my-custom-scrollbar">

<table class="table is-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Acquired year</th>
      <th>Model name</th>
      <th>Model number</th>
      <th>Serial number</th>
      <th>Location</th>
      <th>Manufacturer</th>
      <th>Country of origin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if not @search_equipments.nil? %>
    <% @search_equipments.each do |equipment| %>
      <tr>
        <td><%= equipment.name %></td>
        <td><%= equipment.acquired_year %></td>
        <td><%= equipment.name_of_model %></td>
        <td><%= equipment.model_number %></td>
        <td><%= equipment.serial_number %></td>
        <td><%= equipment.location %></td>
        <td><%= equipment.manufacturer %></td>
        <td><%= equipment.country_of_origin %></td>
        <td><%= link_to 'Show', equipment %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
        <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>

</table>
</div>

<% if not @search_equipments.nil? %>
<%= paginate @search_equipments  %>
<% end %>

app/views/equipments/show.html.erb
<p id="notice"><td><%= notice %></td></p>

 <table class="table is-striped" width="100%">
   <tr>
    <th>Name</th>
    <td><%= @equipment.name %></td>
   </tr> 
   <tr>
    <tr>
      <th>Department</th>
      <td><%= Department.find_by_id(@equipment.department_id).name %></td>
    </tr>
      <th>Status</th>
      <td><%= @equipment.status %></td>
    </tr>
   <tr>
      <th>Model name</th>
      <td><%= @equipment.name_of_model %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= @equipment.location %></td>
    </tr>
    <tr>
      <th>Manufacturer</th> 
      <td><%= @equipment.manufacturer %></td>
    </tr>
    <tr>
      <th>Country of origin</th> 
      <% if not @equipment.country_of_origin.nil? %>
        <% if not ISO3166::Country[@equipment.country_of_origin].nil? %>
         <td><%= ISO3166::Country[@equipment.country_of_origin].unofficial_names.first  %></td>
         <% else %>
           <td></td>
        <% end %>
      <% else %>
         <td></td>
      <% end %>
    </tr>
    <tr>
      <th>Model number</th> 
      <td><%= @equipment.model_number %></td>
    </tr>
    <tr>
      <th>Serial number</th>
      <td><%= @equipment.serial_number %></td>
    </tr>
    <tr>
      <th>Inventory number</th>
      <td><%= @equipment.inventory_number %></td>
    </tr>
    <tr>
      <th>Acquired year</th> 
      <td><%= @equipment.acquired_year %></td>
    </tr>
    <tr>
      <th>Warranty period</th>
      <td><%= @equipment.warranty_period %></td>
    </tr>
    <tr>
      <th>Additional info</th>
      <td><%= @equipment.additional_info %></td>
    </tr>
    <tr>
      <th>Other info</th>
      <td><%= @equipment.other_info %></td>
    </tr>
    <tr>
      <th>Remark</th>
      <td><%= @equipment.remark %></td>
    </tr>
    <tr>
      <th>Where purchased</th>
      <td><%= @equipment.where_purchased %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @equipment.description %></td>
    </tr>
    <tr>
      <th>Price US$</th>
      <td><%= number_with_delimiter(@equipment.price, :delimiter => ',') %></td>
    </tr>
    <tr>
      <th>Internal number</th>
      <td><%= @equipment.internal_number %></td>
    </tr>
  </table> 

<% if current_user.role=="admin" %>
  <td><%= link_to 'Edit', edit_equipment_path(@equipment) , class: 'button is-success'%></td> 
<% end %>