config/routes.rb
Rails.application.routes.draw do
  resources :equipments
  resources :dealers
  resources :items
  resources :services
  resources :billings
  resources :maintenances
  # devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'home/index'
  root 'home#index'
  get 'acknowledgement', to: 'maintenances#acknowledgement'
  get 'followup', to: 'maintenances#followup'
  get 'survey', to: 'home#survey'
  get 'service', to: 'home#service', as: 'all_service'
  get 'search', to: 'equipments#search'
  get 'download_pdf', to: "home#download_pdf"
  get 'about', to: "home#about"
  get 'staff', to: "home#staff"
  get 'summary', to: "home#summary"
  get 'dashboard', to: "home#dashboard"
  put 'maintenance_cancel_request/:id', to: "maintenances#cancel_request", as: 'maintenance_cancel_request'
  get 'cancel_request_received/:id', to: 'maintenances#cancel_request_received', as: 'cancel_request_received'
  get 'equipments/:id/archive/', to: "equipments#archive", as: 'archive_equipment'
  get 'equipments/:id/unarchive/', to: "equipments#unarchive", as: 'unarchive_equipment'
  get 'sign_up_confirmation', to: 'home#sign_up_confirmation', as: 'sign_up_confirmation'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about, :staff, :sign_up_confirmation]
  before_action :authenticate_admin_user!, only: [:dashboard]

  def index
    
  end

  def home

  end


  def summary
    @q = Maintenance.all
    
    if(params[:report])
      @month = params[:report]["month(2i)"]
      @year = params[:report]["year(1i)"]
    else
      @month = ''
      @year = ''
    end

    if(@month.blank?)
      @month_name = ''
      if (@year.blank?) 
        # month and year is blank -> use this year
        @year = Date.today.year
        beginning_of_year = Date.today.beginning_of_year
        beginning_of_last_month = Date.today.end_of_year.next_month
        @requested_maintenances = @q.where(created_at: beginning_of_year..beginning_of_last_month)
        @completed_maintenances = @q.where(created_at: beginning_of_year..beginning_of_last_month).where.not(completed_at: nil)
      else
        # month blank but year exists -> use parameter year
        beginning_of_year = Date.new(@year.to_i)
        beginning_of_last_month = beginning_of_year.end_of_year.next_month
        @requested_maintenances = @q.where(created_at: beginning_of_year..beginning_of_last_month).page(params[:page]) 
        @completed_maintenances = @q.where(created_at: beginning_of_year..beginning_of_last_month).where.not(completed_at: nil)
      end
    else
      @month_name = Date::MONTHNAMES[@month.to_i]
      beginning_of_month = Date.new(@year.to_i,@month.to_i,1)
      beginning_of_next_month = beginning_of_month.next_month
      @requested_maintenances = @q.where(created_at: beginning_of_month..beginning_of_next_month).page(params[:page]) 
      @completed_maintenances = @q.where(created_at: beginning_of_month..beginning_of_next_month).where.not(completed_at: nil)
    end

    ids = @requested_maintenances.pluck(:equipment_id)
    tmp_equipments = Equipment.find(ids)
    new_equipments = ids.map {|x| tmp_equipments.detect {|b| b.id == x } }
    ids = new_equipments.pluck(:department_id)
    tmp_departments = Department.find(ids)
    new_departments = ids.map {|x| tmp_departments.detect {|b| b.id == x } }
    ary = new_departments.pluck(:name)
    @departments = ary.each_with_object(Hash.new(0)){|v,o| o[v]+=1}

    ids = @completed_maintenances.pluck(:equipment_id)
    tmp_equipments = Equipment.find(ids)
    new_equipments = ids.map {|x| tmp_equipments.detect {|b| b.id == x } }
    ids = new_equipments.pluck(:department_id)
    tmp_departments = Department.find(ids)
    new_departments = ids.map {|x| tmp_departments.detect {|b| b.id == x } }
    ary = new_departments.pluck(:name)
    @departments2 = ary.each_with_object(Hash.new(0)){|v,o| o[v]+=1}

  end
  
  def service

  end

  def sign_up_confirmation

  end

  def dashboard
    @q = Maintenance.ransack(params[:q]) 
    @search_maintenances = @q.result(distinct: true).where(completed_at: nil).where(canceled_at: nil).page(params[:page]) 
    @search_maintenances_completed = @q.result(distinct: true).where.not(completed_at: nil).page(params[:page]) 
    @search_maintenances_canceled = @q.result(distinct: true).where.not(canceled_at: nil).page(params[:page]) 
  end

  def staff

  end

  def about

  end

  def download_pdf
    send_file "#{Rails.root}/public/complaint_form.pdf", type: "application/pdf", x_sendfile: true
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1 class="is-size-4" style="margin-bottom: 20px;">About CeSEM</h1>

<p><b>CeSEM (Center for Scientific Equipment Maintenance)</b> is a technology centre based at the <a href="http://jkuat.ac.ke/">Jomo Kenyatta University of Agriculture and Technology (JKUAT)</a> in Kenya.</p>
<br/>

<p>  The purpose of the centre is to carry out maintenance and to ensure optimal performance of all scientific equipment in the university. A proposal to initially host CeSEM at the Innovation and Prototyping Integrated Centre (iPIC) was approved by the University Senate. The fact that the University Senate projected the growth of the centre to a directorate status in future emphasizes the importance this would have on academic and research outcomes. </p>
<br/>

<p> A good number of equipment repair and maintenance initiated with the help of Japan International Cooperation Agency (JICA) through <a href="http://jkuat.ac.ke/projects/africa-ai-japan/">AFRICA-ai-JAPAN project</a> has led to the operationalization of quite a number of equipment that are currently being effectively used for teaching and research activities, thereby saving the university colossal amounts and availing the relevant tools for academic excellence.</p>
<br/>

<p>Respective departments requiring CeSEM services will be responsible for the costs incurred in maintaining their equipment.  This would ensure sustainability of the centre.</p>

app/views/home/dashboard.html.erb
<h1 class="is-size-4">Requested maintenances</h1>


<div class="tabs is-boxed">
  <ul>
    <li class="maintenances is-active">
      <a>
        <span>Maintenances</span>
      </a>
    </li>
    <li class="maintenances-completed">
      <a>
        <span>Completed maintenances</span>
      </a>
    </li>
    <li class="maintenances-canceled">
      <a>
        <span>Canceled maintenances</span>
      </a>
    </li>
  </ul>
</div>


<table class="table is-striped">
  <thead>
    <tr>
      <th>Trace number</th>
      <th>Requester</th>
      <th>Equipment name</th>
      <th>Department</th>
      <th>Status</th>
      <th>Scheduled</th>
      <th>Completion expected</th>
      <th>Recommission projected</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @search_maintenances.each do |maintenance| %>     
    <tr class="maintenances-table">
      <td><%= maintenance.trace_number   %></td>
      <td><%= User.find_by_id(maintenance.user_id).name %></td>
      <td><%= Equipment.find_by_id(maintenance.equipment_id).name %></td>
      <td><%= Department.find_by_id(Equipment.find_by_id(maintenance.equipment_id).department_id).name %></td>
      <td><%= maintenance.status %></td>
      <% if not maintenance.scheduled_at.nil?  %>
        <td><%= maintenance.scheduled_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if not maintenance.completion_expected_at.nil?  %>
        <td><%= maintenance.completion_expected_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if not maintenance.recommission_projected_at.nil?  %>
        <td><%= maintenance.recommission_projected_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
        <td><%= link_to 'Update status', edit_maintenance_path(maintenance),  class: 'button' %></td>
    </tr>
    <% end %>
    <% @search_maintenances_completed.each do |_maintenance| %>     
    <tr class="maintenances-completed-table">
      <td><%= _maintenance.trace_number   %></td>
      <td><%= User.find_by_id(_maintenance.user_id).name %></td>
      <td><%= Equipment.find_by_id(_maintenance.equipment_id).name %></td>
      <td><%= Department.find_by_id(Equipment.find_by_id(_maintenance.equipment_id).department_id).name %></td>
      <td><%= _maintenance.status %></td>
      <% if not _maintenance.scheduled_at.nil?  %>
        <td><%= _maintenance.scheduled_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if not _maintenance.completion_expected_at.nil?  %>
        <td><%= _maintenance.completion_expected_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if not _maintenance.recommission_projected_at.nil?  %>
        <td><%= _maintenance.recommission_projected_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
        <td><%= link_to 'Update status', edit_maintenance_path(_maintenance),  class: 'button' %></td>
    </tr>
    <% end %>
    <% @search_maintenances_canceled.each do |__maintenance| %>     
    <tr class="maintenances-canceled-table">
      <td><%= __maintenance.trace_number   %></td>
      <td><%= User.find_by_id(__maintenance.user_id).name %></td>
      <td><%= Equipment.find_by_id(__maintenance.equipment_id).name %></td>
      <td><%= Department.find_by_id(Equipment.find_by_id(__maintenance.equipment_id).department_id).name %></td>
      <td><%= __maintenance.status %></td>
      <% if not __maintenance.scheduled_at.nil?  %>
        <td><%= __maintenance.scheduled_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if not __maintenance.completion_expected_at.nil?  %>
        <td><%= __maintenance.completion_expected_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
      <% if not __maintenance.recommission_projected_at.nil?  %>
        <td><%= __maintenance.recommission_projected_at.strftime("%d/%m/%Y") %></td>
      <% else %>
        <td></td>
      <% end %>
        <td><%= link_to 'Update status', edit_maintenance_path(__maintenance),  class: 'button' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @search_maintenances %>

app/views/home/index.html.erb
<h1 class="is-size-3 has-text-centered" style="margin-bottom: 40px;">Welcome to CeSEM Digital System</h1>   

<ul class="bxslider">
	<div><%=image_tag "landing/3dp.png", width: '600px' %></div>
  <div><%=image_tag "landing/printed.png", width: '600px' %></div>
  <div><%=image_tag "landing/spectrometer.png", width: '600px' %></div>
	<div><%=image_tag "landing/macharia.png", width: '600px' %></div>
	<div><%=image_tag "landing/masinde.png", width: '600px' %></div>
	<div><%=image_tag "landing/nderi.png", width: '600px' %></div>
	<div><%=image_tag "landing/ff_exp_bench.png", width: '600px' %></div>
	<div><%=image_tag "landing/pc.png", width: '600px' %></div>
  <div><%=image_tag "landing/ups.png", width: '600px' %></div>
	<div><%=image_tag "landing/microscope.png", width: '600px' %></div>
	<div><%=image_tag "landing/microscope2.png", width: '600px' %></div>
</ul>


<footer class="footer" style="height:200px;margin-top: 60px;">
    <div class="bd-footer-links" style="margin-top: -40px;">
      <div class="columns">
        <div class="column is-5">
            <h3 class="is-size-6"><b>Links</b></h3>

            <p class="bd-footer-link-title">
                <a href="http://www.jkuat.ac.ke/">Jomo Kenyatta University of Agriculture and Technology</a>
            </p>

            <p class="bd-footer-link-title">
                <a href="http://www.jkuat.ac.ke/colleges/engineering/">College of Engineering and Technology (COETEC)</a>
            </p>

            <p class="bd-footer-link">
              <a href="http://jkuat.ac.ke/projects/africa-ai-japan/">AFRICA-ai-JAPAN Project</a>
            </p>

            <p class="bd-footer-link">
              <a href="https://www.facebook.com/jicakenya/">JICA Kenya</a>
            </p>

        </div>
      </div>
        <div class="has-text-centered" style="margin-top: -20px;">
         <small>&copy; Copyright 2019, Center for Scientific Equipment Maintenance (CeSEM), JKUAT</small>
      </div>
    </div>
</footer>

app/views/home/service.html.erb
<div class="columns is-centered">
  <div class="column is-one-fifth">
    <h3 class="is-size-5">Summary this month</h3>
    <p>Total request: <%= Maintenance.where(created_at: Date.today.beginning_of_month..Date.today.end_of_month).count %></p>
    <p>Maintenance completed: <%= Maintenance.where(completed_at: Date.today.beginning_of_month..Date.today.end_of_month).count %></p>
  </div>

  <div class="column">
   <div style="margin:20px 0px; border: 2px solid hsl(141, 71%, 48%); border-radius: 10px; padding: 20px;">

     <h1 class="is-size-3 has-text-danger has-text-centered">Main menu</h1>

     <p class="is-size-5 has-text-centered has-text-white" style="background-color: hsl(204, 86%, 53%);padding: 5px;margin-top: 10px;">Kindly select one option</p>

     <div class="has-text-danger is-size-5" style="padding: 5px;"><%= link_to 'Equipment list', equipments_path %></div>
     <div class="has-text-danger is-size-5" style="padding: 5px;"><%= link_to 'Add new equipment', new_equipment_path %></div>
     <div class="has-text-danger is-size-5" style="padding: 5px;"><a href="/followup">Request follow-up</a></div>
     <div class="has-text-danger is-size-5" style="padding: 5px;"><%= link_to 'Billing', billings_path %></div>
     <div class="has-text-danger is-size-5" style="padding: 5px;"><a href="/survey">Customer Satisfaction Survey</a></div>

     <% if current_user.role=='admin' %>
       <p class="is-size-5 has-text-centered has-text-white" style="background-color: hsl(14, 100%, 53%); padding: 5px;margin-top: 10px;">Admin section</p>
       <div class="has-text-danger is-size-5" style="padding: 5px;"><a href="/dashboard">Update maintenance status</a></div>
       <div class="has-text-danger is-size-5" style="padding: 5px;"><a href="/billings/new">Create Billing</a></div>
       <div class="has-text-danger is-size-5" style="padding: 5px;"><a href="/summary">Statistics</a></div>
     <% end %>
   </div>
 </div>

  <div class="column is-one-fifth">
    <h3 class="is-size-5">Latest activity</h3>
    <%= image_tag 'landing/pc.png' %>
    <h4 class="">Computer</h4>
    <%= image_tag 'landing/microscope2.png', {style: 'margin-top:20px;'}%>
    <h4 class="">Microscope</h4>
  </div>

</div>

app/views/home/sign_up_confirmation.html.erb
  <h1 class="is-size-4" style="margin:40px 0;">Sign up success</h1>
  
  <p>Thank you for signing up for the CeSEM digital system.</p>
  <p>We have sent you an e-mail for the confirmation. Kindly check your e-mail inbox and click the link in the e-mail to activate your account.</p>

app/views/home/staff.html.erb
<h1 class="is-size-4" style="margin-bottom: 20px;">Staff</h1>

<p class="is-size-5" style="margin-bottom: 10px;">Head of Section</p>

<figure class="image is-128x128">
    <%= image_tag 'mr_omondi.png', class: "is-rounded" %>
</figure>
<p>Mr. Daniel Omondi</p>
<br/>

<p class="is-size-5" style="margin-bottom: 10px;">Maintenance Engineers</p>

<div class="columns">
 <div class="column is-one-fifth"> 
    <figure class="image is-128x128">
        <%= image_tag 'mr_masinde.png', class: "is-rounded" %>
    </figure>
    <p>Mr. David Masinde</p>
</div>
<div class="column is-one-fifth"> 
    <figure class="image is-128x128">
        <%= image_tag 'mr_macharia.png', class: "is-rounded" %>
    </figure>
    <p>Mr. David Macharia</p>
</div>
<div class="column is-one-fifth"> 
    <figure class="image is-128x128">
        <%= image_tag 'mr_nderi.png', class: "is-rounded" %>
    </figure>
    <p>Mr. David Nderi</p>
</div>
</div>

<p class="is-size-5" style="margin-bottom: 10px;">Technical advisor</p>
<p>Dr. Shohei Aoki (AFRICA-ai-JAPAN Project)</p>

app/views/home/summary.html.erb
<h1 class="is-size-4">Report for <%= @month_name %> <%= @year %> </h1>

<%= form_tag('summary', method: :get) do %>
<div class="field">
  <%= date_select("report", "month", order: [:month], selected: Date.today, include_blank: true) %>
  <%= date_select("report", "year", order: [:year], selected: Date.today, include_blank: false) %>
  <%= submit_tag 'Filter' , class: 'button' %>
  <%= link_to 'Clear', '/summary', class: 'button' %>
</div>
<% end %>

<p>Requested maintenance: <%= @requested_maintenances.count %></p>
<%= pie_chart @departments %>

<p>Completed maintenance: <%= @completed_maintenances.count %></p> 
<%= pie_chart @departments2 %>

<p>Detail of completed maintenance</p>
<table class="table" style="font-size: 0.8rem;">
  <thead>
    <tr>
     <th>Department</th>
     <th>Equipment name</th>
     <th>Manufacturer</th>
     <th>Model name</th>
     <th>Model number</th>
     <th>Serial number</th>
     <th>Inventory number</th>
     <th>Location</th>
     <th>Year acquired</th>
     <th>Country of origin</th>
     <!-- <th>Requester</th> -->
     <!-- <th>Request date</th> -->
     <th>Expert's diagnosis</th>
     <th>Date of completion</th>
   </tr>
 </thead>
 <tbody>
  <% @completed_maintenances.each do |m| %>
   <tr>
    <td><%= Department.find_by_id(Equipment.find_by_id(m.equipment_id).department_id).name %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).name %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).manufacturer %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).name_of_model %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).model_number %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).serial_number %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).inventory_number %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).location %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).acquired_year %></td>
    <td><%= Equipment.find_by_id(m.equipment_id).country_of_origin %></td>
    <!-- <td><%= User.find_by_id(m.user_id).name %></td> -->
    <!-- <td><%= m.created_at.strftime("%d/%m/%Y") %></td> -->
    <td><%= m.diagnosis %></td>
    <td><%= m.completed_at %></td>
  </tr>
  <% end %>
</tbody>

</table>

app/views/home/survey.html.erb
  <h1 class="is-size-4" style="margin:40px 0;">Customer Satisfaction Survey</h1>
  
  <p>Kindly let us know whether you are satisfied with services received from CeSEM by clicking the link below and filling in form 1-9-1.</p>
  <p>We would be glad to hear from you.</p>

  <p style="margin-top:20px;">Customer Complement / Complaint Form [F-1-9-1]</p>

  <%= link_to "download", download_pdf_path %>

  <p style="margin-top:20px;">You can send an e-mail to us by attaching the form: <%= mail_to 'cesem@jkuat.ac.ke' %></p>